# Generated by Django 5.1.3 on 2024-11-18 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_car_slug'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='car',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
    ]
