# Generated by Django 5.1.3 on 2024-11-18 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_car_slug'),
        ('comment', '0002_comment_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='car.car'),
        ),
    ]
