# Generated by Django 5.1.3 on 2024-11-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
